---
title: Gebruik het tekstgereedschap
hero_image: images/banner.png
description: Gebruik het tekstgereedschap om tekst toe te voegen aan uiterlijken en achtergronden
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Gebruik het tekstgereedschap
