title: scratch3-use-text-tool
hero_image: images/banner.png
description: scratch3-use-text-tool description
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Introduction
  - title: Step title
  - title: What next?
