title: Use the Text tool
hero_image: images/banner.png
description: Use the text tool to add text to costumes and backdrops.
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Use the Text tool
