---
title: Verwende das Text-Werkzeug
hero_image: images/banner.png
description: Verwende das Text-Werkzeug, um Text zu Kostümen und Hintergründen hinzuzufügen
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Verwende das Text-Werkzeug
