---
title: Utilize a ferramenta de Texto
hero_image: images/banner.png
description: Utilize a ferramenta de Texto para adicionar texto à fantasias e cenários
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Utilize a ferramenta de Texto
