---
title: Text tool ಅನ್ನು ಬಳಸಿ
hero_image: images/banner.png
description: ವಸ್ತ್ರಗಳು ಮತ್ತು ಬ್ಯಾಕ್‌ಡ್ರಾಪ್‌ಗಳಿಗೆ ಪಠ್ಯವನ್ನು ಸೇರಿಸಲು Text tool ಅನ್ನು ಬಳಸಿ
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Text tool ಅನ್ನು ಬಳಸಿ
