---
title: Usa la herramienta de texto
hero_image: images/banner.png
description: Use la herramienta texto para agregar texto a los disfraces y fondos
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Usa la herramienta de texto
