---
title: Użyj narzędzia Tekst
hero_image: images/banner.png
description: Użyj narzędzia Tekst, aby dodać tekst do kostiumów i tła
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Użyj narzędzia Tekst
