---
title: Använd textverktyget
hero_image: images/banner.png
description: Använd textverktyget för att lägga till text i klädslar och bakgrunder
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Använd textverktyget
