---
title: Utiliser l'outil Texte
hero_image: images/banner.png
description: Utiliser l'outil de Texte pour ajouter du texte aux costumes et aux arrières plans
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - 
    title: Utiliser l'outil Texte
