---
title: Usa lo strumento Testo
hero_image: images/banner.png
description: Usa lo strumento Testo per aggiungere testo a costumi e sfondi
version: 4
listed: false
copyedit: false
last_tested: "2021-03-12"
steps:
  - title: Usa lo strumento Testo
